### ISSUE TITLE
KeyError: 'EncoderDecoder_Distill is not in the models registry'

### ISSUE THREAD

**Issue by Reversev** [xzz777/SCTNet#18]
I try to run this command "python tools/test.py configs/sctnet/ADE20K/sctnet-s_8x4_160k_ade.py weights/SCTNet-S-ADE20K.pth --eval mIoU". But it cannot work.

```
2024-03-03 12:41:01,105 - mmseg - INFO - Multi-processing start method is `None`
2024-03-03 12:41:01,105 - mmseg - INFO - OpenCV num_threads is `8
2024-03-03 12:41:01,129 - mmseg - INFO - Loaded 2000 images
Traceback (most recent call last):
  File "/SCTNet/tools/test.py", line 323, in <module>
    main()
  File "/SCTNet/tools/test.py", line 221, in main
    model = build_segmentor(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/mmsegmentation-0.26.0/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'EncoderDecoder_Distill is not in the models registry'
```

I think this is problem about mmseg registry. Can you help me?

**Comment by xzz777** [comment]
This is indeed an issue with the mmseg registry, and it seems that you have already installed a version of mmseg in your conda environment. This is related to the knowledge of Python import order. 
You are actually importing the build_segmentor from the pre-installed mmseg repository in your conda environment, wherethe EncoderDecoder_Distill is not registered. You can debug step by step and observe that the code is directed to the mmseg/models/segmentors/__init__.py in your own mmseg version, rather than the corresponding file in this project.

There are several ways to resolve this issue:
1. Simply move test.py outside the tools folder and then run it.
2. In test.py, add a command to append the path of the SCTNet project to sys.path (note that the SCTNet path should be added before the mmseg environment path).
3. If you are familiar enough with the mmseg library, you can integrate the corresponding parts of SCTNet into it and register accordingly.

**Comment by Reversev** [comment]
Thanks a lot, I've got it.

**Comment by dlydly111** [comment]
您好，能详细说说KeyError: 'EncoderDecoder_Distill is not in the models registry'的具体解决方法吗？？？我看不懂原作者的解决方法 很抱歉

**Comment by gujiuren** [comment]
> 您好，能详细说说KeyError: 'EncoderDecoder_Distill is not in the models registry'的具体解决方法吗？？？我看不懂原作者的解决方法 很抱歉

可以用作者所说的第二种方法，再import mmseg之前使用
import sys
sys.path.append(“当前路径")

**Comment by Wheezily** [comment]
thank you

**Comment by AAAdecade** [comment]
您好，请问复现的结果能达到原文的精度吗

**Comment by leoriczhang** [comment]
> 您好，请问复现的结果能达到原文的精度吗

我复现了所有模型都没达到

**Comment by AAAdecade** [comment]
> > 您好，请问复现的结果能达到原文的精度吗
> 
> 我复现了所有模型都没达到

是的，我的复现也没有达到

**Comment by leoriczhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已收到！
